apiVersion: v1
kind: ReplicationController
metadata:
#  namespace: default
  name: zipkin
  labels:
    name: zipkin
spec:
  replicas: 1
  selector:
    name: zipkin
  template:
    metadata:
      labels:
        name: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 9411
