

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: registry
  labels:
    app: registry
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 5000
  selector:
    app: registry