apiVersion: apps/v1
kind: StatefulSet
metadata:
  #  namespace: default
  name: registry
  labels:
    app: registry
spec:
  serviceName: registry
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:latest
          resources:
            limits:
              cpu: 150m
              memory: 4000Mi
            requests:
              cpu: 100m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: vol-data
              mountPath: /var/lib/registry
      volumes:
        - name: vol-data
          hostPath:
              path: /www/k8s/foxdev/registry/data
              type: Directory