

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: registry-ui
  labels:
    app: registry-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 5010
  selector:
    app: registry-ui