

apiVersion: v1
kind: Service
metadata:
  #  namespace: default
  name: rmqbroker
  labels:
    app: rmqbroker
spec:
  type: NodePort
  ports:
    - port: 10909
      targetPort: 10909
      nodePort: 10909
      name: slave-master
    - port: 10911
      targetPort: 10911
      nodePort: 10911
      name: listen
    - port: 10912
      targetPort: 10912
      nodePort: 10912
      name: ha-service
  selector:
    app: rmqbroker