

apiVersion: v1
kind: Service
metadata:
  #  namespace: default
  name: rocketmq
  labels:
    app: rocketmq
spec:
  type: NodePort
  ports:
    - port: 9876
      targetPort: 9876
      nodePort: 9876
  selector:
    app: rocketmq