

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: prometheus
  labels:
    name: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 9090
  selector:
    name: prometheus