

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: grafana
  labels:
    name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000
  selector:
    name: grafana