apiVersion: v1
kind: ReplicationController
metadata:
#  namespace: default
  name: sentinel
  labels:
    name: sentinel
spec:
  replicas: 1
  selector:
    name: sentinel
  template:
    metadata:
      labels:
        name: sentinel
    spec:
      containers:
        - name: sentinel
          image: foxiswho/sentinel
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 400m
              memory: 768Mi
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: sentinel-cm
                  key: sentinel.server.host
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: sentinel-cm
                  key: sentinel.server.port
          ports:
            - containerPort: 8280
          volumeMounts:
            - name: vol-log
              mountPath: /opt/logs
      volumes:
        - name: vol-log
          hostPath:
            path: /www/k8s/foxdev/sentinel/logs
            type: Directory