

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: sentinel
  labels:
    name: sentinel
spec:
  type: NodePort
  ports:
    - port: 8280
      targetPort: 8280
      nodePort: 8280
  selector:
    name: sentinel

