

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 6379
  selector:
    app: redis